alias ll="ls -al";
alias .="cd ..";
alias rbld="cd ~/nixdots;git add .; sudo nix flake update; sudo nixos-rebuild switch --flake .  --option eval-cache false";
# rbld = "nix-update";
alias pmx="pulsemixer";
# rbld = "nix-update";
alias v="nvim";
# v = "nix run 'github:elythh/nixvim'";
alias sng="sudo nix-collect-garbage -d";
alias ng="nix-collect-garbage  --delete-old";
alias zrc="nvim ~/nixdots/modules/terminal/zsh/default.nix";
alias ndc="nvim ~/nixdots";
alias hrc="nvim ~/nixdots/configs/hypr/hyprland.conf";
alias nd="nix develop path:$(pwd)";
alias nus="nixupdateswitch.sh";
alias alx="nvim ~/nixdots/modules/terminal/zsh/alias.zsh"
alias spkgs="nvim ~/nixdots/pkgs/system.nix"
alias hpkgs="nvim ~/nixdots/pkgs/home.nix"
alias hx="start-hyprland"
# alias btop="btop --utf-force"
alias hs="$HOME/bin/hotspot"
alias clr="clear"
