# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/859e297b-724e-4b4e-9de2-a7bd9c664004";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/573E-3DDC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/05416415-0d92-479c-80cd-5d2a36818699";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5c5813f8-7022-4e6f-8890-e3156c8cf0b1"; }
    ];

  fileSystems."/mnt/win1" =
    { device = "/dev/disk/by-uuid/06CE2FB0CE2F96C9";
      fsType = "ntfs";
    };

  fileSystems."/mnt/win2" =
    { device = "/dev/disk/by-uuid/0880AE1480AE07F0";
      fsType = "ntfs";
    };

      fileSystems."/mnt/win3" =
    { device = "/dev/disk/by-uuid/7CB45F57B45F12CE";
      fsType = "ntfs";
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
