---@diagnostic disable: undefined-global
-- This is the converted Hyprland Lua config.
-- Converted from the provided .conf without changing active values or commands.

require("animations")
require("autostart")
require("decoration")
require("env")
require("general")
require("inputs")
require("monitor")
require("rules")
require("keybinds")

-- hl.monitor({
-- 	output = "",
-- 	mode = "1920x1080@144",
-- 	position = "0x0",
-- 	scale = 1,
-- })
--
-- -- workspace=DP-2,1
--
-- -- See https://wiki.hyprland.org/Configuring/Keywords/ for more
--
-- -- Execute your favorite apps at launch
--
-- -- exec-once = waybar & hyprpaper & firefox
--
-- -- Source a file (multi-file configs) source = ~/.config/hypr/myColors.conf
--
-- -- Some default env vars. env = XCURSOR_SIZE,24
--
-- hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
-- hl.env("HYPRCURSOR_SIZE", "24")
-- hl.env("HYPRSHOT_DIR", "$HOME/Screenshots")
--
-- -- env = GDK_BACKEND wayland,x11
--
-- -- For all categories, see https://wiki.hyprland.org/Configuring/Variables/
--
-- hl.config({
-- 	input = {
-- 		kb_layout = "us",
-- 		kb_variant = "",
-- 		kb_model = "",
-- 		kb_options = "",
-- 		kb_rules = "",
--
-- 		follow_mouse = 1,
-- 		force_no_accel = 1,
--
-- 		touchpad = {
-- 			natural_scroll = false,
-- 		},
--
-- 		sensitivity = 1.25, -- -1.0 - 1.0, 0 means no modification.
-- 	},
-- })
--
-- hl.config({
-- 	general = {
-- 		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
--
-- 		gaps_in = 5,
-- 		gaps_out = 20,
-- 		border_size = 3,
--
-- 		col = {
-- 			active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
-- 			inactive_border = "rgba(595959aa)",
-- 		},
--
-- 		layout = "scrolling",
--
-- 		-- allow_workspace_cycles = true
-- 	},
-- })
--
-- -- decoration {
-- --
-- -- # See https://wiki.hyprland.org/Configuring/Variables/ for more
-- --
-- -- rounding = 10
-- -- blur = yes
-- -- blur_size = 3
-- -- blur_passes = 1
-- -- blur_new_optimizations = on
-- --
-- -- drop_shadow = yes
-- -- shadow_range = 4
-- -- shadow_render_power = 3
-- -- col.shadow = rgba(1a1a1aee)
-- -- }
--
-- hl.config({
-- 	decoration = {
-- 		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
--
-- 		rounding = 5,
--
-- 		blur = {
-- 			enabled = true,
-- 			size = 3,
-- 			passes = 5,
-- 			-- blurls = gtk-layer-shell
-- 			-- blurls = Discord
-- 			-- blurls = rofi
-- 			-- blurls = waybar
-- 			new_optimizations = true,
-- 		},
--
-- 		shadow = {
-- 			enabled = true,
-- 			range = 4,
-- 			render_power = 3,
-- 			color = "rgba(1a1a1aee)",
-- 		},
-- 	},
-- })
--
-- hl.config({
-- 	animations = {
-- 		enabled = true,
--
-- 		-- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
-- 	},
-- })
--
-- -- hl.curve("myBezier", {
-- -- 	type = "bezier",
-- -- 	points = {
-- -- 		{ 0.05, 0.9 },
-- -- 		{ 0.1, 1.05 },
-- -- 	},
-- -- })
-- --
-- -- hl.curve("linear", {
-- -- 	type = "bezier",
-- -- 	points = {
-- -- 		{ 0.0, 0.0 },
-- -- 		{ 1.0, 1.0 },
-- -- 	},
-- -- })
-- --
-- -- hl.curve("liner", {
-- -- 	type = "bezier",
-- -- 	points = {
-- -- 		{ 1.0, 1.0 },
-- -- 		{ 1.0, 1.0 },
-- -- 	},
-- -- })
-- --
-- -- hl.animation({
-- -- 	leaf = "windows",
-- -- 	enabled = true,
-- -- 	speed = 7,
-- -- 	bezier = "myBezier",
-- -- })
-- --
-- -- hl.animation({
-- -- 	leaf = "windowsOut",
-- -- 	enabled = true,
-- -- 	speed = 7,
-- -- 	bezier = "default",
-- -- 	style = "popin 80%",
-- -- })
-- --
-- -- hl.animation({
-- -- 	leaf = "border",
-- -- 	enabled = true,
-- -- 	speed = 5,
-- -- 	bezier = "liner",
-- -- })
-- --
-- -- hl.animation({
-- -- 	leaf = "borderangle",
-- -- 	enabled = true,
-- -- 	speed = 8,
-- -- 	bezier = "liner",
-- -- 	once = true,
-- -- })
-- --
-- -- hl.animation({
-- -- 	leaf = "fade",
-- -- 	enabled = true,
-- -- 	speed = 7,
-- -- 	bezier = "default",
-- -- })
-- --
-- -- hl.animation({
-- -- 	leaf = "workspaces",
-- -- 	enabled = true,
-- -- 	speed = 6,
-- -- 	bezier = "default",
-- -- })
--
-- hl.config({
-- 	dwindle = {
-- 		-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
-- 		-- pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
-- 		preserve_split = true, -- you probably want this
-- 	},
-- })
--
-- hl.config({
-- 	master = {
-- 		-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
-- 		new_status = "slave",
-- 	},
-- })
--
-- hl.config({
-- 	scrolling = {
-- 		column_width = 0.5,
-- 		direction = "right",
-- 		fullscreen_on_one_column = true,
-- 		focus_fit_method = 1,
-- 		explicit_column_widths = "0.5, 1.0",
-- 		follow_focus = true,
-- 	},
-- })
--
-- hl.config({
-- 	gestures = {
-- 		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
-- 		-- workspace_swipe = off
-- 	},
-- })
--
-- hl.config({
-- 	binds = {
-- 		allow_workspace_cycles = true,
-- 	},
-- })
--
-- -- Example per-device config
--
-- -- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
--
-- hl.device({
-- 	name = "razer-razer-viper-mini",
-- 	sensitivity = -0.5,
-- })
--
-- hl.device({
-- 	name = "synaptics-tm3276-022",
-- 	natural_scroll = true,
-- })
--
-- -- Example windowrule v1
--
-- -- windowrule = float, ^(kitty)$
--
-- -- Example windowrule v2
--
-- -- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
--
-- -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
--
-- -- See https://wiki.hyprland.org/Configuring/Keywords/ for more
--
-- local mainmod = "super"
--
-- -- example binds, see https://wiki.hyprland.org/configuring/binds/ for more
--
-- hl.bind(mainmod .. " + return", hl.dsp.exec_cmd("kitty"))
-- hl.bind(mainmod .. " + shift + q", hl.dsp.window.close())
-- hl.bind(mainmod .. " + shift + e", hl.dsp.exit())
-- hl.bind(mainmod .. " + e", hl.dsp.exec_cmd("nautilus"))
-- hl.bind(mainmod .. " + v", hl.dsp.window.float({ action = "toggle" }))
--
-- -- hl.bind(mainmod .. " + d", hl.dsp.exec_cmd("wofi --show drun"))
-- --
-- hl.bind(mainmod .. " + d", hl.dsp.exec_cmd("tofi-drun --drun-launch=true --font /usr/share/fonts/ttf/sf-pro.ttf"))
-- -- hl.bind(
-- -- 	mainmod .. " + d",
-- -- 	hl.dsp.exec_cmd("tofi-drun --font /usr/share/fonts/ttf/sf-pro.ttf| xargs hyprctl dispatch exec --")
-- -- )
--
-- -- hl.bind(mainmod .. " + d", hl.dsp.exec_cmd("rofi -show drun"))
--
-- -- hl.bind(mainmod .. " + p", hl.dsp.window.pseudo()) -- dwindle
-- -- hl.bind(mainmod .. " + j", hl.dsp.layout("togglesplit")) -- dwindle
-- hl.bind(mainmod .. " + f", hl.dsp.window.fullscreen({ mode = 1 }))
--
-- -- move focus with mainmod + hjkl keys
--
-- hl.bind(mainmod .. " + h", hl.dsp.focus({ direction = "left" }))
-- hl.bind(mainmod .. " + l", hl.dsp.focus({ direction = "right" }))
-- hl.bind(mainmod .. " + j", hl.dsp.focus({ direction = "up" }))
-- hl.bind(mainmod .. " + k", hl.dsp.focus({ direction = "down" }))
--
-- -- move window with mainmod + hjkl keys
--
-- -- hl.bind(mainmod .. " + shift + h", hl.dsp.window.move({ direction = "left" }))
-- -- hl.bind(mainmod .. " + shift + l", hl.dsp.window.move({ direction = "right" }))
-- -- hl.bind(mainmod .. " + shift + j", hl.dsp.window.move({ direction = "up" }))
-- -- hl.bind(mainmod .. " + shift + k", hl.dsp.window.move({ direction = "down" }))
--
-- -- move window left and right
-- hl.bind(mainmod .. " + shift + l", hl.dsp.layout("swapcol r"))
-- hl.bind(mainmod .. " + shift + h", hl.dsp.layout("swapcol l"))
--
-- -- window resize
-- hl.bind(mainmod .. "+ equal", hl.dsp.layout("colresize +conf"))
--
-- -- switch workspaces with mainmod + [0-9]
--
-- hl.bind(mainmod .. " + 1", hl.dsp.focus({ workspace = 1 }))
-- hl.bind(mainmod .. " + 2", hl.dsp.focus({ workspace = 2 }))
-- hl.bind(mainmod .. " + 3", hl.dsp.focus({ workspace = 3 }))
-- hl.bind(mainmod .. " + 4", hl.dsp.focus({ workspace = 4 }))
-- hl.bind(mainmod .. " + 5", hl.dsp.focus({ workspace = 5 }))
-- hl.bind(mainmod .. " + 6", hl.dsp.focus({ workspace = 6 }))
-- hl.bind(mainmod .. " + 7", hl.dsp.focus({ workspace = 7 }))
-- hl.bind(mainmod .. " + 8", hl.dsp.focus({ workspace = 8 }))
-- hl.bind(mainmod .. " + 9", hl.dsp.focus({ workspace = 9 }))
-- hl.bind(mainmod .. " + 0", hl.dsp.focus({ workspace = 10 }))
--
-- -- move active window to a workspace with mainmod + shift + [0-9]
--
-- hl.bind(mainmod .. " + shift + 1", hl.dsp.window.move({ workspace = 1, silent = true }))
-- hl.bind(mainmod .. " + shift + 2", hl.dsp.window.move({ workspace = 2, silent = true }))
-- hl.bind(mainmod .. " + shift + 3", hl.dsp.window.move({ workspace = 3, silent = true }))
-- hl.bind(mainmod .. " + shift + 4", hl.dsp.window.move({ workspace = 4, silent = true }))
-- hl.bind(mainmod .. " + shift + 5", hl.dsp.window.move({ workspace = 5, silent = true }))
-- hl.bind(mainmod .. " + shift + 6", hl.dsp.window.move({ workspace = 6, silent = true }))
-- hl.bind(mainmod .. " + shift + 7", hl.dsp.window.move({ workspace = 7, silent = true }))
-- hl.bind(mainmod .. " + shift + 8", hl.dsp.window.move({ workspace = 8, silent = true }))
-- hl.bind(mainmod .. " + shift + 9", hl.dsp.window.move({ workspace = 9, silent = true }))
-- hl.bind(mainmod .. " + shift + 0", hl.dsp.window.move({ workspace = 10, silent = true }))
--
-- -- pin
--
-- hl.bind(mainmod .. " + shift + p", hl.dsp.window.pin())
--
-- -- scroll through existing workspaces with mainmod + scroll
--
-- hl.bind(mainmod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
-- hl.bind(mainmod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
--
-- -- workspace back and forth
--
-- hl.bind("super + tab", hl.dsp.focus({ workspace = "previous" }))
--
-- -- hide active window
--
-- -- hl.bind(mainmod .. " + shift + h", hl.dsp.exec_cmd("you script ./scripts/hide_unhide.sh h"))
-- --
-- -- -- show hide window
-- --
-- -- hl.bind(mainmod .. " + shift + h", hl.dsp.exec_cmd("you script ./scripts/hide_unhide.sh s"))
--
-- -- move/resize windows with mainmod + lmb/rmb and dragging
--
-- hl.bind(mainmod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
-- hl.bind(mainmod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
--
-- hl.bind("super + alt + f", hl.dsp.exec_cmd("firefox"))
-- hl.bind("super + alt + z", hl.dsp.exec_cmd("zen-browser"))
-- hl.bind("super + alt + b", hl.dsp.exec_cmd("brave"))
-- hl.bind(
-- 	"super + alt + c",
-- 	hl.dsp.exec_cmd(
-- 		"chromium --incognito --disable-gpu-driver-bug-workarounds --enable-features=useozoneplatform --ozone-platform=wayland"
-- 	)
-- )
-- hl.bind("super + alt + t", hl.dsp.exec_cmd("telegram-desktop"))
-- hl.bind("super + alt + s", hl.dsp.exec_cmd("ld_preload=/usr/local/lib/spotify-adblock.so spotify"))
--
-- -- token
--
-- hl.bind(
-- 	"super + alt + shift + t",
-- 	hl.dsp.exec_cmd('cat /mnt/win1/myself/repo_key | wl-copy; notify-send "token copied"')
-- )
-- hl.bind(
-- 	"super + alt + shift + r",
-- 	hl.dsp.exec_cmd("sed -n '2p' /mnt/win1/myself/emails/reddit.txt | wl-copy; notify-send \"username copied\"")
-- )
-- hl.bind(
-- 	"super + alt + shift + p",
-- 	hl.dsp.exec_cmd("sed -n '3p' /mnt/win1/myself/emails/reddit.txt | wl-copy; notify-send \"password copied\"")
-- )
--
-- -- music
--
-- hl.bind("super + insert", hl.dsp.exec_cmd("playerctl play-pause"))
-- hl.bind("super + delete", hl.dsp.exec_cmd("playerctl stop"))
-- hl.bind("super + home", hl.dsp.exec_cmd("playerctl next"))
-- hl.bind("super + end", hl.dsp.exec_cmd("playerctl previous"))
--
-- -- sound
--
-- hl.bind(
-- 	"super + prior",
-- 	hl.dsp.exec_cmd(
-- 		"pulsemixer --change-volume +2 --max-volume 100 && pactl get-sink-volume @default_sink@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}' > /tmp/wobpipe"
-- 	)
-- )
-- hl.bind(
-- 	"super + next",
-- 	hl.dsp.exec_cmd(
-- 		"pulsemixer --change-volume -2 --max-volume 100 && pactl get-sink-volume @default_sink@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}' > /tmp/wobpipe"
-- 	)
-- )
-- hl.bind("super + shift + m", hl.dsp.exec_cmd('pulsemixer --toggle-mute && notify-send "toggle mute"'))
--
-- -- speaker
--
-- hl.bind("super + pause", hl.dsp.exec_cmd("~/bin/audio_switcher.sh"))
--
-- -- screenshot
--
-- hl.bind("super + print", hl.dsp.exec_cmd('grimblast copysave output && notify-send "screenshot captured"'))
-- hl.bind("super + shift + s", hl.dsp.exec_cmd('grimblast copysave area && notify-send "screenshot captured"'))
--
-- -- screen record
--
-- hl.bind("super + f9", hl.dsp.exec_cmd("screenrecord.sh"))
--
-- -- cliphist
--
-- hl.bind("super + shift + c", hl.dsp.exec_cmd("cliphist list | dmenu | cliphist decode | wl-copy"))
--
-- -- pc
--
-- hl.bind("ctrl + alt + shift + p", hl.dsp.exec_cmd("poweroff"))
-- hl.bind("ctrl + alt + shift + r", hl.dsp.exec_cmd("reboot"))
-- hl.bind("ctrl + alt + shift + h", hl.dsp.exec_cmd("halt"))
-- hl.bind("ctrl + alt + shift + s", hl.dsp.exec_cmd("suspend"))
--
-- -- hyprland
--
-- hl.bind("super + f5", hl.dsp.exec_cmd('hyprctl reload;notify-send "reloaded"'))
--
-- -- hyprpicker
--
-- hl.bind("super + f12", hl.dsp.exec_cmd("hyprpicker -a|wl-copy"))
--
-- -- laptop
--
-- hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd("pactl -- set-sink-volume 0 -10%"))
-- hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd("pactl -- set-sink-volume 0 +10%"))
-- hl.bind("xf86audiomute", hl.dsp.exec_cmd("pactl -- set-sink-mute 0 toggle"))
-- hl.bind("xf86audiomicmute", hl.dsp.exec_cmd("pactl -- set-source-mute 0 toggle"))
-- hl.bind("xf86monbrightnessdown", hl.dsp.exec_cmd("brightnessctl s 10%-"))
-- hl.bind("xf86monbrightnessup", hl.dsp.exec_cmd("brightnessctl s +10%"))
--
-- -- slay the spire
--
-- -- hl.bind("ctrl + alt + s", hl.dsp.exec_cmd("sh downloads/slay.the.spire-jc141/start.n.sh"))
--
-- -- hyprshot
--
-- -- hl.bind(mainmod .. " + print", hl.dsp.exec_cmd("hyprshot -m output | wl-copy"))
-- -- hl.bind(mainmod .. " + shift + print", hl.dsp.exec_cmd("hyprshot -m window | wl-copy"))
--
-- -- pyprland
--
-- hl.bind(mainmod .. " + n", hl.dsp.workspace.toggle_special("stash"))
-- hl.bind(mainmod .. " + shift + n", hl.dsp.exec_cmd("pypr toggle_special stash"))
--
-- -- plugins
--
-- -- hl.config({
-- -- 	plugin = {
-- -- 		hyprfocus = {
-- -- 			enabled = false,
-- --
-- -- 			keyboard_focus_animation = "shrink",
-- -- 			mouse_focus_animation = "shrink",
-- --
-- -- 			bezier = {
-- -- 				bezin = {
-- -- 					type = "bezier",
-- -- 					points = {
-- -- 						{ 0.5, 0.0 },
-- -- 						{ 1.0, 0.5 },
-- -- 					},
-- -- 				},
-- --
-- -- 				bezout = {
-- -- 					type = "bezier",
-- -- 					points = {
-- -- 						{ 0.0, 0.5 },
-- -- 						{ 0.5, 1.0 },
-- -- 					},
-- -- 				},
-- -- 			},
-- --
-- -- 			flash = {
-- -- 				flash_opacity = 0.7,
-- --
-- -- 				in_bezier = "bezin",
-- -- 				in_speed = 0.5,
-- --
-- -- 				out_bezier = "bezout",
-- -- 				out_speed = 3,
-- -- 			},
-- --
-- -- 			shrink = {
-- -- 				shrink_percentage = 0.9,
-- --
-- -- 				in_bezier = "bezin",
-- -- 				in_speed = 1,
-- --
-- -- 				out_bezier = "bezout",
-- -- 				out_speed = 1,
-- -- 			},
-- -- 		},
-- -- 	},
-- -- })
--
-- -- hl.window_rule(
-- --
-- -- match = { class = "org.telegram.desktop" },
-- --
-- -- workspace = "9 silent"
-- --
-- -- )
--
-- hl.window_rule({
-- 	name = "telegram-workspace",
-- 	match = {
-- 		class = "org.telegram.desktop",
-- 	},
-- 	workspace = "9 silent",
-- })
--
-- hl.window_rule({
-- 	name = "discord-workspace",
-- 	match = {
-- 		class = "discord",
-- 	},
-- 	workspace = "8 silent",
-- })
--
-- hl.window_rule({
-- 	name = "qbittorrent-workspace",
-- 	match = {
-- 		class = "org.qbittorrent.qbittorrent",
-- 	},
-- 	workspace = "7 silent",
-- })
--
-- hl.window_rule({
-- 	name = "qbittorrent-float",
-- 	match = {
-- 		class = "org.qbittorrent.qbittorrent",
-- 	},
-- 	float = true,
-- })
--
-- hl.window_rule({
-- 	name = "steam",
-- 	match = {
-- 		class = "steam",
-- 	},
-- 	float = true,
-- })
--
-- -- hl.window_rule({ name = "kitty_starting_width", match = { class = "kitty" }, scrolling_width = 0.75 })
--
-- -- windowrule=opacity 0.95,workspace:[0-9]
--
-- -- windowrulev2=workspace 9 silent,class:org.telegram.desktop
--
-- -- windowrulev2=workspace 8 silent,class:discord
--
-- -- windowrule=workspace 6 silent,class:docker desktop
--
-- -- windowrule=workspace 10 silent,spotify
--
-- -- windowrule=workspace 7 silent,class:obsidian
--
-- -- windowrule=workspace 6 silent,notion-app-enhanced
--
-- -- #windowrule=opacity 0.9,obsidian
--
-- -- #windowrule=opacity 0.9,firefox
--
-- -- windowrule=opacity 0.9,zen
--
-- -- windowrule=opacity 0.1,launcher
--
-- -- windowrulev2=float,class:tk
--
-- -- windowrulev2=float,class:toplevel
--
-- -- layerrule = blur,launcher
--
-- hl.on("hyprland.start", function()
-- 	hl.exec_cmd("discord")
-- end)
--
-- hl.on("hyprland.start", function()
-- 	hl.exec_cmd("telegram-desktop")
-- end)
--
-- hl.on("hyprland.start", function()
-- 	hl.exec_cmd("telegram")
-- end)
--
-- hl.on("hyprland.start", function()
-- 	hl.exec_cmd("qbittorrent")
-- end)
--
-- hl.on("hyprland.start", function()
-- 	hl.exec_cmd("hyprpaper")
-- end)
-- -- exec-once=obsidian
-- hl.on("hyprland.start", function()
-- 	hl.exec_cmd("hyprctl setcursor bibata-modern-ice 24")
-- end)
