require("plugins/scrolloverview")
require("plugins/hyprglass")

-- -- Scroll Overview
-- local plugin = ".config/hypr/plugins/libscrolloverview.so"
-- hl.plugin.load(plugin)
-- hl.config({
-- 	plugin = {
-- 		scrolloverview = {
-- 			gesture_distance = 300, -- how far is the "max" for the gesture
-- 			scale = 0.5, -- preferred overview scale
-- 			workspace_gap = 100,
-- 			layout = "vertical", -- vertical, horizontal, or auto (per-monitor orientation)
-- 			wallpaper = 2, -- 0: global only, 1: per-workspace only, 2: both
-- 			blur = true, -- blur only the main overview wallpaper
--
-- 			shadow = {
-- 				enabled = true,
-- 				range = 50,
-- 			},
-- 		},
-- 	},
-- })
--
-- hl.bind("SUPER + O", function()
-- 	hl.plugin.scrolloverview.overview("toggle all")
-- end)
--
-- hl.define_submap("scrolloverview", function()
-- 	hl.bind("CTRL + h", hl.plugin.scrolloverview.navigate("left"))
-- 	hl.bind("CTRL + l", hl.plugin.scrolloverview.navigate("right"))
-- 	hl.bind("CTRL + k", hl.plugin.scrolloverview.navigate("up"))
-- 	hl.bind("CTRL + j", hl.plugin.scrolloverview.navigate("down"))
-- 	hl.bind("CTRL + u", hl.plugin.scrolloverview.overview("select"))
-- 	hl.bind("escape", hl.plugin.scrolloverview.overview("off"))
-- 	hl.bind("mouse:272", function()
-- 		-- Select the clicked window, or just the workspace if no window was clicked, then close the overview. This is the default behaviour if submap is not defined.
-- 		hl.plugin.scrolloverview.overview("select")
-- 		hl.plugin.scrolloverview.window("select")
-- 		hl.plugin.scrolloverview.overview("off")
-- 	end, { mouse = true })
-- 	hl.bind("mouse:274", hl.plugin.scrolloverview.window("close"), { mouse = true })
-- end)
--
-- -- Example Hyprland bind that keeps working inside the submap:
-- -- for i = 1, 10 do
-- --  local key = i % 10
-- --  hl.bind("ALT + " .. key, hl.dsp.focus({ workspace = i }), { submap_universal = true })
-- -- end
